[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
scraper = "0.18.1"
serde = "1.0.196"
serde_json = "1.0.113"
unicode-segmentation = "1.11.0"
